### ISSUE TITLE
Index.html

### ISSUE THREAD

**Issue by JZLanguageResearchInstitute** [JZLanguageResearchInstitute/jinzhong#2]
<!DOCTYPE html>
<html>
    <head>
        <title>HelloWorld！</title>
    </head>
    <body>
        <nav>
          
        </nav>
        <div class="container">
            <div class="blurb">
                <h1>该页面正在调试中</h1>
                <p>敬请期待</a></p>
            </div>
        </div>
        <footer>
            <ul>
                <li><a href="JZLanguageReIn@outlook.com">email</a></li>
                
            </ul>
        </footer>
    </body>
</html>

**Comment by WendaoLee** [comment]
笑死，叶姐你好可爱。
